swagger: "2.0"
info:
  version: 1.0.0
  title: diary-api
  description: Diary API
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  SigninBody:
    type: object
    title: signin
    required:
      - email
      - password
    properties:
      email:
        type: string
        example: email@email.co
      password:
        type: string
        example: password123
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress
  UserBody:
    type: object
    title: user
    required:
      - name
    properties:
      name:
        type: string
        example: "Andre Lopes"
      username:
        type: string
        example: oandrelopes
      email:
        type: string
        example: "lopes.andree@gmail.com"
      bio:
        type: string
        example: ""
      image:
        type: string
        example: ""
paths:
  /signin:
    post:
      tags:
        - Signin
      description: Signin in App
      parameters:
        - name: email
          in: body
          description: email@email.co
          required: true
          schema: 
            $ref: "#/definitions/SigninBody"
      responses:
        201:
          description: Returns user token

  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification

  /users:
    get:
      tags:
        - Users
      description: Fetch all users
      responses:
        200:
          description: Returns all users
    post:
      tags:
        - Users
      description: Create a new user
      parameters:
        - name: user
          in: body
          description: an user
          required: true
          schema: 
            $ref: "#/definitions/UserBody"
      responses:
        200:
          description: Returns all users